<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: $
 */
return array (
  'Home' => 'Inici',
	'Add new' => '0#Crear nou|1#Crear nova',
  'Create' => 'Crear',
	'View' => 'Veure',
  'Fields with {*} are required.' => 'Els camps marcats amb {*} són obligatoris.',
  'Hello, {name}.' => 'Hola, {name}.',
  'Incorrect username or password.' => 'Nom d\'usuari o contrasenya incorrectes.',
  'Last login:' => 'Darrer login:',
  'Login' => 'Entrar',
  'Password' => 'Contrasenya',
  'Please fill out the following form with your login credentials:' => 'Si us plau, entreu el vostre nom d\'usuari i contrasenya:',
  'Remember me next time' => 'Recordeu-me en aquest ordinador',
  'Save' => 'Guardar',
	'Save Options' => 'Guardar Opcions',
  'Update' => 'Editar',
  'Username' => 'Nom d\'usuari',
  'Welcome, {name}' => 'Benvingut/da, {name}',
  'logout' => 'sortir',
	'Cancel'=>'Cancel·lar',
	'Home'=>'Inici',
);
