<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: $
 */
return array (
  'Categories' => 'Categories',
	'Category' => 'Categoria',
  'City' => 'Població',
  'Description' => 'Descripció',
  'End Date' => 'Data Fi',
  'End Time' => 'Hora Fi',
  'Events' => 'Esdeveniments',
  'Feed' => 'URL',
  'Feed Type' => 'Tipus Feed',
  'Geo Lat' => 'Geo Lat',
  'Geo Lng' => 'Geo Lng',
	'Geo Precision' => 'Geo Precisió',
  'Lang' => 'Idioma',
  'Lat' => 'Lat',
  'Lng' => 'Lng',
  'Location' => 'Localització',
  'Photo' => 'Foto',
	'Photo Local' => 'Foto (local)',
  'Score' => 'Puntuació',
  'Source' => 'Font',
  'Sources' => 'Fonts',
  'Start Date' => 'Data Inici',
  'Start Time' => 'Hora Inici',
  'Summary' => 'Sumari',
  'Tags' => 'Tags',
  'Unique ID' => 'Id. únic', 
  'Cities' => 'Poblacions',
  'Created' => 'Data creació',
  'ID' => 'ID',
  'Name' => 'Nom',
  'Updated' => 'Data modif.',
  'Url' => 'Url',
	'Active' => '0#Actiu|1#Activa',
	'Source Count' => 'Num. fonts',
	'Event Count' => 'Num. esdev.',
	'Schedule' => 'Quan',
	'Address' => 'Adreça',
	'Uid' => 'Uid',
	'City to events' => 'Assignar ciutat a esdeveniments',
	'Num. favorites'=>'Fav.',
	'Num. flagged'=>'Flags',
	'Promoted'=>'Promo',
	'Users'=>'Usuaris',
	'Username'=>'Nom d\'usuari',
	'Full Name'=>'Nom',
	'Last Login'=>'Darrer login',
	'Num. favorites'=>'Favorits',
	'Num. friends'=>'Amics',
	'Source'=>'Origen',
);
